import React from 'react';
import { useGame } from '../context/GameContext';
import ArrowLeftIcon from './icons/ArrowLeftIcon';

const Section: React.FC<{ title: string, children: React.ReactNode }> = ({ title, children }) => (
    <div className="bg-zinc-800 p-4 rounded-lg">
        <h2 className="text-xl font-bold text-red-400 mb-3">{title}</h2>
        <div className="space-y-2 text-zinc-300 text-sm leading-relaxed">
            {children}
        </div>
    </div>
);

const GameGuideView: React.FC = () => {
    const { dispatch } = useGame();

    return (
        <div className="h-screen w-full bg-zinc-900 overflow-y-auto">
            <header className="p-4 flex items-center gap-4 sticky top-0 bg-zinc-900/80 backdrop-blur-sm z-10 border-b border-zinc-700/50">
                <button onClick={() => dispatch({ type: 'CHANGE_VIEW', payload: 'game' })} className="p-2 rounded-full hover:bg-white/10">
                    <ArrowLeftIcon className="w-6 h-6" />
                </button>
                <h1 className="text-2xl font-bold">Game Guide</h1>
            </header>
            <main className="p-4 space-y-6">
                <Section title="Getting Started">
                    <p><strong>Recording Songs:</strong> Head to the 'Studio' app to record your first song. Choose a studio that balances cost and quality. Higher quality songs perform better.</p>
                    <p><strong>Song Quality:</strong> This number (0-100) is the most important factor for a song's success. It's determined by the studio you use and a bit of luck.</p>
                </Section>
                <Section title="Releasing Music">
                    <p><strong>Singles, EPs, Albums:</strong> Once you have unreleased songs, go to the 'Release Hub' app to package them. Singles are one song, EPs are 3-7, and Albums are 8+.</p>
                    <p><strong>Independent vs. Label:</strong> Releasing independently gives you full control but less promotional power. Signing to a label requires you to submit music for approval, but they provide a significant boost to your streams.</p>
                </Section>
                 <Section title="Building Your Career">
                    <p><strong>Hype:</strong> Generated by new releases, gigs, and promotional activities. Hype decays over time. High hype boosts your stream numbers across your entire catalog.</p>
                    <p><strong>Popularity:</strong> A long-term measure of your fame. It grows with consistent success and decays slowly if you don't release music. It boosts streams, sales, and social media engagement.</p>
                    <p><strong>Promotions:</strong> Use the 'Promote' app to run campaigns for your songs and videos. This costs money weekly but provides a multiplier on your streams/views.</p>
                    <p><strong>Gigs:</strong> Perform live shows via the 'Gigs' app to earn immediate cash and hype. You can only perform one gig per week.</p>
                </Section>
                <Section title="Charts & Streams">
                    <p><strong>Billboard Hot 100:</strong> The main song chart. It's updated weekly. Songs are ranked based on their weekly stream counts.</p>
                    <p><strong>Recurrent Rule:</strong> A song is removed from the Hot 100 if it has been on the chart for 20+ weeks AND falls below position #50. This keeps the chart fresh.</p>
                    <p><strong>Album Charts:</strong> Based on "album equivalent units". This is a combination of song streams from the album and pure sales (from merch like vinyls and CDs).</p>
                </Section>
                 <Section title="Social Media & Awards">
                    <p><strong>X (formerly Twitter):</strong> Use the 'X' app to interact with fans, start fan wars, and see what the media is saying about you. Your posts can generate buzz.</p>
                    <p><strong>GRAMMYs & VMAs:</strong> Each year, you'll get an email to submit your work for awards consideration. Winning awards provides a huge boost to your career.</p>
                </Section>
            </main>
        </div>
    );
};

export default GameGuideView;
